services:
  postgres:
    image: postgres:17.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_dev:
